type CategoryChildren = {
  uid: string,
  name: string,
  path: string,
  url_key: string,
  url_path: string,
  position: number,
  image: null | string,
  display_mode: string,
  image_banner: string,
  product_count: number,
  children_count: string,
  include_in_menu: number,
  meta_title: null | string,
  canonical_url: null | any,
  path_in_store: null | any,
  description: null | string,
  meta_keywords: null | string,
  available_sort_by: null | any,
  meta_description: null | string,
  breadcrumbs: {
    category_uid: string,
    category_name: string,
    category_level: number,
    category_url_key: string,
    category_url_path: string,
  }[] | null,
}

type CategoryMainChildren = CategoryChildren & {
  children: CategoryChildren[],
}

type Category = {
  uid: string,
  name: string,
  path: string,
  position: number,
  image: null | any,
  display_mode: string,
  product_count: number,
  url_key: null | string,
  children_count: string,
  url_path: null | string,
  include_in_menu: number,
  breadcrumbs: null | any,
  icon_image: null | string,
  meta_title: null | string,
  path_in_store: null | any,
  canonical_url: null | any,
  description: null | string,
  meta_keywords: null | string,
  children: CategoryMainChildren[],
  available_sort_by: null | any,
  meta_description: null | string,
}
